### ISSUE TITLE
Maybe add option to load fontawesome from cdnjs?

### ISSUE THREAD

**Issue by MechanisM** [alexgleason/wagtailfontawesome#11]
Here is [link](https://cdnjs.com/libraries/font-awesome)

**Comment by alexgleason** [comment]
We're using a [modified version](https://github.com/alexgleason/wagtailfontawesome/blob/master/wagtailfontawesome/static_src/wagtailfontawesome/scss/wagtailfontawesome.scss) of FontAwesome.
