### ISSUE TITLE
pypi

### ISSUE THREAD

**Issue by sannykr** [alexgleason/wagtailfontawesome#13]
Could you please make it available on pypi. I can't find the source over there.

**Comment by sannykr** [comment]
@synapticarbors:  This package is not available on pypi. Could you please tell me how to proceed with this.

**Comment by alexgleason** [comment]
It's right here https://pypi.python.org/pypi/wagtailfontawesome

**Comment by sannykr** [comment]
This is just .whl file, but I was looking for source.

**Comment by alexgleason** [comment]
I don't know how to do that or why it's valuable. The source is available in this repo.

**Comment by sannykr** [comment]
I am trying to build it on conda-forge, and the source is downloaded from pypi. I will figure out how to proceed if source is not on PYPI.

**Comment by synapticarbors** [comment]
Another option is to have a source release directly on Github:

https://help.github.com/articles/creating-releases/

See also:
https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos

**Comment by alexgleason** [comment]
I created a release on Github. If you'd like me to publish the source on PyPi please tell me the steps. Or if either of you would like editor access on PyPi let me know.

**Comment by sannykr** [comment]
@alexgleason : Thanks. I will use the release.

**Comment by FlipperPA** [comment]
I have published to PyPI version 1.0.7, and included a `.tar.gz` source file of the publish as well as a wheel, @sannykr. I think we can close this issue.

**Comment by alexgleason** [comment]
@FlipperPA how did you publish including the .tar.gz? I just merged another PR and want to update it on PyPi but not sure how to.

**Comment by FlipperPA** [comment]
In addition to doing a `python setup.py bdist` you can do this:

```bash
python setup.py sdist
python setup.py bdist_wheel
twine upload dist/mypackage-0.1.1*
```

I hope that helps!
