### ISSUE TITLE
tar.gz package fails to install without npm/gulp

### ISSUE THREAD

**Issue by gasman** [alexgleason/wagtailfontawesome#21]
Running `pip install` on the .tar.gz version of the package fails on a system without a global installation of npm / gulp - this is because the installation process calls the `python setup.py egg_info` command, which triggers the npm build.

    $ pip install https://pypi.python.org/packages/b8/45/bc2cacc434c579d8dfb80a829d330ca83b97269efc12cbccd80832b86b3a/wagtailfontawesome-1.1.1.tar.gz#md5=a396d0775ca8eae185fd83d43afdf8c7
    Collecting https://pypi.python.org/packages/b8/45/bc2cacc434c579d8dfb80a829d330ca83b97269efc12cbccd80832b86b3a/wagtailfontawesome-1.1.1.tar.gz#md5=a396d0775ca8eae185fd83d43afdf8c7
      Using cached wagtailfontawesome-1.1.1.tar.gz
        Complete output from command python setup.py egg_info:
        running egg_info
        npm ERR! path /private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-y7DmTG-build/package.json
        npm ERR! code ENOENT
        npm ERR! errno -2
        npm ERR! syscall open
        npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-y7DmTG-build/package.json'
        npm ERR! enoent This is related to npm not being able to find a file.
        npm ERR! enoent

        npm ERR! A complete log of this run can be found in:
        npm ERR!     /Users/matthew/.npm/_logs/2017-11-27T15_01_58_649Z-debug.log
        Error compiling assets: Command '[u'npm', u'run', u'build']' returned non-zero exit status 254

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/p6/_51b92q88xj9kk0059bc8f3h0000gn/T/pip-y7DmTG-build/

(Related: when I try to build the package myself, it's missing README.md since that's not listed in MANIFEST.in, and so setup fails at the point where it tries to build `long_description` from the readme. However, README.md _is_ present in the current release .tar.gz, so I guess your build process is slightly different from mine...)

**Comment by alexgleason** [comment]
Pinging @timheap

**Comment by FlipperPA** [comment]
Aha, we should probably just distribute the wheel then. @alexgleason Why did we start distributing the .tar.gz? I know I built it but can't remember why we were doing it. Thanks @gasman!

**Comment by alexgleason** [comment]
@FlipperPA It's because of #13, someone has some kind of build process that requires it

**Comment by gasman** [comment]
PR for the 'npm install' issue submitted (#22) - I can't replicate the issue with the readme now, so not sure what was going on there.
