### ISSUE TITLE
Could the releases be tagged?

### ISSUE THREAD

**Issue by iaindillingham** [alexgleason/wagtailfontawesome#24]
Hopefully not too onerous, especially with [bumpversion][]. It would help compare between releases.

[bumpversion]: https://pypi.python.org/pypi/bumpversion

**Comment by alexgleason** [comment]
Hi @iaindillingham, sorry for the late response. Please see #25

**Comment by alexgleason** [comment]
Okay, we're tagging releases now!

**Comment by iaindillingham** [comment]
Thank you!
