### ISSUE TITLE
Add contributing section to README

### ISSUE THREAD

**Issue by alexgleason** [alexgleason/wagtailfontawesome#25]
So, I'm a bit inexperienced with publishing Python packages. I just tried updating the package and realized I [broke the README](https://pypi.python.org/pypi/wagtailfontawesome) on PyPi.

I've also gotten requests to upload source files to pypi #13 and tag releases #24.

I always forget how to publish the package and have to look it up before doing so. But it looks like there are several different ways and maybe I'm not doing it right. So I was hoping someone with more experience could add info on how to publish the package in the README. I'm thinking something as simple as, "here's a list of commands you can run to upload the package."

Here's essentially what I did for the 1.1.2 release which broke the README:

```
python3 setup.py bdist_wheel
twine upload dist/*
```

Thanks!

**Comment by timheap** [comment]
I've made a wiki page to help contributors make a release: <https://github.com/alexgleason/wagtailfontawesome/wiki/Making-a-new-release>. Combined with #27, releasing packages with correctly formatted READMEs should now be straight forward.

**Comment by alexgleason** [comment]
This is beautiful. Just uploaded version 1.1.3 and it's looking great!
