### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by jjanssen** [alexgleason/wagtailfontawesome#7]
I have `wagtailfontawesome` as a dependency within my project, defined as: `wagtailfontawesome>=1.0` together with wagtail 1.6.

Whenever I run an install I get the following error:
`error: [Errno 2] No such file or directory: u'/tmp/wagtailfontawesome-1.0.3/README.md'`

**Comment by alexgleason** [comment]
I'm having trouble reproducing this

**Comment by jjanssen** [comment]
Let me see if I can create a consolidated reproduction.

**Comment by jjanssen** [comment]
Nevermind. Turns out it was illegally running `easy_install` during a process. 😔
